Task general
grace-p-03/grace-p-03.github.io pull request #1
Opened 2022-01-18 11:32 UTC by grace-p-03

Please ignore 'about' section, it's not responsive yet and I'll work on that next!

I've added my  HTML & CSS for the base structure of the nav, header, about, projects, contact and footer so far.

2022-01-18 12:05 UTC, gabrielrowan commented on normalize.css
> +  display: block;
Do you need display block here? As block is the default

2022-01-18 12:26 UTC, gabrielrowan requested changes
There wasn't a lot I could find to comment on here - basically just indentation and a line that I'm not sure is necessary 

I think the indentation is optional to change as it doesn't affect how the website works

2022-01-18 12:26 UTC, gabrielrowan commented on portfolio.html
> +	      <a href="#contact">Contact</a>
This could be indented in line with the other  links

2022-01-18 12:26 UTC, gabrielrowan commented on portfolio.html
> +		</header>
The closing and opening header tag have different indentation

2022-01-18 12:26 UTC, gabrielrowan commented on style.css
> +	top: 0;
Is there a reason for the top: 0 and left: 0 here? What do you need to achieve by including them?

2022-01-18 12:26 UTC, gabrielrowan commented on portfolio.html
> +		      <h2>About me</h2>
Do your h2 and img tag need the same indentation?

2022-01-18 12:26 UTC, gabrielrowan commented on portfolio.html
> +			<div class="projectsIntro">
Do your opening and closing divs need the same indentation?

2022-01-19 10:54 UTC, ethan-garrett approved these changes
Looks good to me

2022-01-19 10:56 UTC, merged